plugin:liquidglass {
    enabled = 1
    exclude_classes = mpv,helium
    layer_namespaces = quickshell

    window_opacity = 0.84
    layer_opacity = 1.0
    layer_corner_radius = 14
    glass_opacity = 0.84

    blur_strength = 0.28
    blur_iterations = 2

    refraction_strength = 1.35
    chromatic_aberration = 1.10
    lens_distortion = 1.35

    fresnel_strength = 0.62
    specular_strength = 0.56
    edge_thickness = 0.052

    tint_color = 0xb8d8ff00

    brightness = 0.84
    contrast = 1.22
    saturation = 1.18
    vibrancy = 0.42
    adaptive_dim = 0.42
    adaptive_boost = 0.08
}
