plugin:liquidglass {
    enabled = 1
    exclude_classes = mpv,helium

    window_opacity = 0.94
    glass_opacity = 0.64

    blur_strength = 0.18
    blur_iterations = 2

    refraction_strength = 1.50
    chromatic_aberration = 1.45
    lens_distortion = 1.45

    fresnel_strength = 0.30
    specular_strength = 0.48
    edge_thickness = 0.050

    tint_color = 0xb8d8ff00

    brightness = 0.58
    contrast = 1.42
    saturation = 1.28
    vibrancy = 0.72
    adaptive_dim = 0.62
    adaptive_boost = 0.00
}
